
import "./globals.css";
import Layout from "./components/layouts/Layout";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">

      <body className="font-Vazir">
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
